### ISSUE TITLE
Questions about the data set

### ISSUE THREAD

**Issue by LiuShiWang** [mitiku1/EyeOpenDetection#3]
The code you shared helped me a lot.
thank you!
I want to see the actual effect.
Can you share the data set for me?
my mail address is 2293643065@qq.com
thanks again

**Comment by ymitiku** [comment]
Hi LiuShiWang,
Thanks for being interested in my code. Here is [the link]
(http://parnec.nuaa.edu.cn/xtan/data/ClosedEyeDatabases.html) to dataset
I've used.
Regards
Mitiku

**Comment by LiuShiWang** [comment]
Thank you very much for your letter.
Put the data in the directory and the code won't work properly.
I noticed that the code has to import ‘pkl’ data, do I need to convert ’jpg‘ to ’pkl‘ in advance?

**Comment by ymitiku** [comment]
Hey @LiuShiWang I've added readme file to solve this confusion could you look into it?.
